### ISSUE TITLE
test unique_xf_series_to_seed_series_id fails

### ISSUE THREAD

**Issue by yeslawr2** [matsonj/nba-monte-carlo#89] opened 2023-07-13 23:34 UTC
**Environment**: Ubuntu 20.04.6 via WSL

**Command**: `make docker-run-evidence` and `make docker-run-superset`

**Description**:  When `meltano invoke dbt-duckdb build` is called when running the docker container, the test unique_xf_series_to_seed_series_id fails. The same test passes without using docker. Here are the messages which show up in the terminal after the 75 tests are completed:

```
23:19:50  Running 1 on-run-end hook
23:19:51  Statements to run:
23:19:51  1 of 1 START hook: nba_monte_carlo.on-run-end.0 ................................ [RUN]
23:19:51  1 of 1 OK hook: nba_monte_carlo.on-run-end.0 ................................... [OK in 0.00s]
23:19:51
23:19:51
23:19:51  Finished running 7 table models, 10 external models, 41 tests, 17 view models, 1 hook in 0 hours 0 minutes and 32.05 seconds (32.05s).
23:19:51
23:19:51  Completed with 1 error and 0 warnings:
23:19:51
23:19:51  Failure in test unique_xf_series_to_seed_series_id (models/_docs.yml)
23:19:51    Got 14 results, configured to fail if != 0
23:19:51
23:19:51    compiled Code at ../docs/compiled/nba_monte_carlo/models/_docs.yml/unique_xf_series_to_seed_series_id.sql
23:19:51
23:19:51  Done. PASS=68 WARN=0 ERROR=1 SKIP=6 TOTAL=75
```

**Comment by matsonj** [comment] 2023-07-14 01:01
I'll take a look! What is weird here is that means the file is loaded twice into docker somehow. I'll try to repro in the next few days.

**Comment by matsonj** [comment] 2023-07-14 23:20
I can reproduce this, but I don’t believe it is an issue.

If you run the project in a codespace, Docker imports the files from your codespace into the container. Specifically, [this line of code in the dockerfile](https://github.com/matsonj/nba-monte-carlo/blob/9353a6c736b7dc2a6dd55629f14a355e002c8dfb/Dockerfile#L34). 

If you run the project in the codespace, with something like ```make build pipeline``` and then do ```make docker-build```, the files in your working directory will be copied into docker. This is not really the behavior that I want, but since the working directories are shared between the codespace and docker, not a whole lot I can do. This project is designed to work locally OR in a codespace OR in docker OR in docker in a codespace, but not in a codespace AND docker in a codespace. 

The error is because ```make pipeline``` ran in the codespace, copying the data to the local working directory. Then ```make docker-build``` copied the working directory into the docker container. Then ```make docker-run-evidence``` (or superset, or rill) duplicated those records into the working directory, because meltano state is not shared between the codespace and docker container. Thus, the test failed because the data existed twice, when it should have only existed once. 

I’m happy to take a PR on this if you want to fix it, so let me know your thoughts, otherwise I will close it.

**Comment by yeslawr2** [comment] 2023-07-15 23:16
That makes sense. Also, I tried deleting and re-cloning the repo, then performing the docker commands and it worked. I was trying to run it locally before running the docker version when this error occurred (which is probably why `make pipeline` was run before the docker commands).

If this is not an issue, then there may not be need for a PR. You can go ahead and close the issue. Thank you for the explanation!

**Closed as completed** 2023-07-23 17:45 UTC
